import Footer from "@/components/footer/Footer";
import Navbar from "@/components/navbar/Navbar";
import { Inter } from "next/font/google";
import "./globals.css";
import "./reset.css";
import { ThemeContext, ThemeContextProvider } from "@/context/teameToggle";
import Providers from "@/providers/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} max-w-[100vw] overflow-x-hidden bg-white dark:bg-slate-800 dark:text-textColor `}
      >
        <Providers>
          <div className="min-h-[100vh] bg-bg text-textColor ">
            <div className="warpper">
              <Navbar />
              {children}
              <Footer />
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
